#Write a function called fallingDistance() that accepts an objects falling time (in seconds) as an argument.
# The function should print distance.

fallingTime = input("How long is the object falling?: ")
def fallingDistance(fallingTime):
    for counter in range(1, fallingTime + 1):
        d = (1 / 2) * 9.8 * counter ** 2
        print d


fallingDistance(fallingTime);



#Generate multiplication tables for a user entered 'n'; user should also specify the number of rows desired

number = input("What number would you like to multiply?: ")
rows = input("How many rows would you like to multiply this number?: ")
print"--Multiplication Table--"
print"Generate multiplication time table for: ", number
print"Stop table at: ", rows
for counter in range(1, rows + 1):
    solution = number*counter
    print number, "times", counter, "=", solution
print"--End--"

#Calculate and average with a loop that asks for inputs depending on number of scores generated by user

totalScore = 0
noOfScores = input("Enter number of scores: ")
for counter in range(noOfScores):
    number = input("Please enter the next score: ");
    totalScore = totalScore + number;
    avg = totalScore/noOfScores
print("The total is: ", avg);